### ISSUE TITLE
Code reorganization

### ISSUE THREAD

**Issue by Tycharis** [smithb99/football-project#2]
Splitting code into multiple files

**Comment by daytonltaylor** [comment]
Acceptance Criteria:
- There should be no commented code that is not otherwise needed.
- Commonly accessed namespaces should be included into the file instead fo constantly accessed from the namespace itself.
- For loop incrementation should be consistent if it does not negatively affect the functionality of the rest of the code. ex) ++i OR i++

**Comment by Tycharis** [comment]
Closed by #6
